One-Click Start
reiase/FlagPerf pull request #6
Opened 2023-09-07 09:06 UTC by dayuyuhai

1.修改resnet50权重下载网址为158server
2.增加README.md
3.修改config_R300x1x8.py
4.修改environment_variables.sh

2023-09-07 09:23 UTC, xiaohan4420 commented on training/benchmarks/retinanet/pytorch/model/__init__.py
> +            'resnet50'] = 'http://10.1.2.158:8111/flagperf/resnet50-0676ba61.pth'
需要改回pytorch官方地址

2023-09-07 09:29 UTC, xiaohan4420 commented on training/kunlunxin/retinanet-pytorch/config/environment_variables.sh
> +#export XLOG_LEVEL="capture=info"
没用的环境变量可以清理掉

2023-09-07 16:34 UTC, reiase requested changes

2023-09-07 16:34 UTC, reiase commented on training/kunlunxin/retinanet-pytorch/config/environment_variables.sh
> +pip uninstall -y xmlir || true
这几个install不进智源的PR，我们交付文档里边给到智源

2023-09-07 16:34 UTC, reiase commented on training/kunlunxin/retinanet-pytorch/config/config_R300x1x8.py
> +
需要添加1x1和2x8的优化

2023-09-07 16:34 UTC, reiase commented on training/kunlunxin/retinanet-pytorch/README.md
> +| 单机2卡  | config_R300x1x2 |      |       |    |     |             |
只保留1x1 1x8 2x8 三个配置，并且补充1x8的收敛精度，性能数据并不透出

2023-09-11 06:47 UTC, KungYork commented on training/kunlunxin/retinanet-pytorch/README.md
> +| 单机8卡  | config_R300x1x8 |      	   |   0.35   |  0.3525  |         |                  |
这里把内存占用也加上一列相应的数据吧

2023-09-11 06:51 UTC, KungYork commented on training/kunlunxin/retinanet-pytorch/README.md
> +| 单机8卡  | config_R300x1x8 |      	   |   0.35   |  0.3525  |         |                  |
README的相关内容要不参考cpm&glm，把一些指标解释和相应的一些性能指标再完善一下吧

2023-09-11 06:51 UTC, GGuanl commented on training/kunlunxin/retinanet-pytorch/README.md
> +### 运行情况
可能需要添加通用指标和性能指标做到一致性

2023-10-30 10:13 UTC, closed without merging